### ISSUE TITLE
Length of thread?

### ISSUE THREAD

**Issue by mescude** [nataliefreed/stab-bindings-designer#11]
Hey there, maybe this is overkill but we thought it might be nice if the app made a suggestion for how long your thread needs to be once your design is done- assuming your are stitching.

**Comment by nataliefreed** [comment]
Yes!!! We also wanted to include an estimated time to stitch, by having the user enter the time it takes them to stitch one hole and having the app multiply this by the number of holes. Yet another way to help connect the digital tools to physical objects and processes.

**Comment by nataliefreed** [comment]
To start with: goal is to report this in units of book width (so you can still print your book out at any size).
