### ISSUE TITLE
Quadrille view option?

### ISSUE THREAD

**Issue by mescude** [nataliefreed/stab-bindings-designer#12]
Hi Natalie!
When making symmetrical designs or repeating patterns, its hard to make sure holes are lined up properly. Have you considered an option to view the workspace with a quadrille overlay?

Thanks!
Meg

**Comment by nataliefreed** [comment]
This is a great suggestion. "Snap to grid" would be helpful to go with this. @hooperpk also suggested tools to repeat patterns of holes rather than doing it manually, I will add that as another issue.
